version: '3.9'

services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: pulsaciones
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  fastapi-backend:
    container_name: fastapi-backend
    image: fastapi/backend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres-container
    restart: always
    ports:
      - ${PORT}:${PORT}

  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - "5050:80"
